### ISSUE TITLE
Unable to locate package wiringpi

### ISSUE THREAD

**Issue by almulder** [robertalexa/U6143_ssd1306#2]
unable to install as when I try to install wiringpi I get an error

**Comment by robertalexa** [comment]
Hi,

Could you provide some more details? 

So you have to follow these instructions:
![image](https://user-images.githubusercontent.com/9019306/140940620-83a7eb52-4681-4880-aa6d-4e31a89f598e.png)

If you have issues with wiringpi after following that, then you can try:
![image](https://user-images.githubusercontent.com/9019306/140940701-c087485f-fded-4446-ada9-c4b309dafde3.png)

**Comment by almulder** [comment]
correct the wiringPi code you listed, it will not get. However I just found this and it now works.:

```
wget https://project-downloads.drogon.net/wiringpi-latest.deb
sudo dpkg -i wiringpi-latest.deb
```
That allowed me to get a working copy of wiringPi installed.

**Comment by robertalexa** [comment]
What do you mean it will not get? Do you have git installed in the first place? `sudo apt install git`

**Comment by almulder** [comment]
Yes I have git installed, cant remember the exact message, but it was saying it was not found. But its working now with the other one I installed. Also from what I found the one I posted is the last official version, no a fork. 

[[](http://wiringpi.com/wiringpi-updated-to-2-52-for-the-raspberry-pi-4b/)](http://wiringpi.com/wiringpi-updated-to-2-52-for-the-raspberry-pi-4b/)

**Comment by robertalexa** [comment]
No Idea, the link you have provided is from June 2019. In August 2019 wiringPi was deprecated. So if that would be the latest available, then sudo apt install wiringpi should do the trick. The workaround I have used on the x64 version of the OS.

Anyway, glad all is working for you. This isn't really a project that i look after, just forked it for personal use but more than happy to share it with others
